apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: local-dev-project
  credentials:
    source: AccessToken
    secretRef:
      namespace: crossplane-system
      name: gcp-credentials
      key: creds