apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-sql-minisky
spec:
  deploymentTemplate:
    spec:
      selector:
        matchLabels:
          runtime-config: provider-gcp-sql-minisky
      template:
        metadata:
          labels:
            runtime-config: provider-gcp-sql-minisky
        spec:
          containers:
            - name: package-runtime
              env:
                - name: GOOGLE_SQL_CUSTOM_ENDPOINT
                  value: http://minisky-sql-proxy.crossplane-system.svc.cluster.local:8080/